### ISSUE TITLE
Unnecessary aliases for FHIR resources

### ISSUE THREAD

**Issue by markkramerus** [FHIR/GoFSH#113] opened 2021-05-13 18:25 UTC
GoFSH is defining unnecessary* aliases for base FHIR resources, e.g.:

Alias: $Identifier = http://hl7.org/fhir/StructureDefinition/Identifier
Alias: $Composition = http://hl7.org/fhir/StructureDefinition/Composition
Alias: $Endpoint = http://hl7.org/fhir/StructureDefinition/Endpoint
Alias: $HealthcareService = http://hl7.org/fhir/StructureDefinition/HealthcareService
Alias: $Observation = http://hl7.org/fhir/StructureDefinition/Observation
Alias: $PractitionerRole = http://hl7.org/fhir/StructureDefinition/PractitionerRole

One complicating factor is that this IG defines a profile named "Composition" that is based on Composition (really horrible style), so maybe this is necessary??

https://github.com/afourquet/us-odh/commit/40c7487a2cb61ac9ecc75ede4c21815be60fcda7

**Comment by mint-thompson** [comment] 2021-08-20 15:59
Unfortunately, I think these aliases are necessary. I verified that each of these aliases corresponds to a FHIR resource that shares a name with a resource defined in the IG:
- Identifier: input/resources/structuredefinition/obf-datatype-Identifier-extension.json
- Composition: input/resources/structuredefinition/obf-Composition.json
- Endpoint: input/resources/structuredefinition/obf-Endpoint.json
- HealthcareService: input/resources/structuredefinition/obf-HealthcareService.json
- Observation: input/resources/structuredefinition/obf-Observation.json
- PractitionerRole: input/resources/structuredefinition/obf-PractitionerRole.json

This behavior is expected based on the test case that asserts GoFSH [should not resolve a URL to the name of a core FHIR resource if it shares a name with a local StructureDefinition](https://github.com/FHIR/GoFSH/blob/master/test/optimizer/utils.test.ts#L97-L104).

**Comment by jafeltra** [comment] 2024-09-06 15:46
Closing this issue since the aliases were confirmed as necessary.

**Closed by jafeltra** 2024-09-06 15:46 UTC
Labels: added to backlog
